// Code generated by hertz generator.

package user

import (
	"Hospital/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newuserMw() []app.HandlerFunc {

	return auth.Auth(2)
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _doctorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedoctorMw() []app.HandlerFunc {
	return auth.Auth(0)
}

func _nurseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatenurseMw() []app.HandlerFunc {
	return auth.Auth(0)
}

func _queryuserlistMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(0)
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateadminMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(2)
}
