// Code generated by hertz generator.

package main

import (
	"Hospital/biz/dal"
	"Hospital/biz/middleware/jwt"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
	dal.Init()
	jwt.Init()
}
func main() {
	h := server.Default()

	register(h)
	h.Spin()
}
