// Code generated by hertz generator.

package clinical

import (
	"Hospital/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return auth.Auth(0)
}

func _clinicalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _caseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _diagnoseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddiagnoseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _patientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addpatientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _symptomMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addsymptomMw() []app.HandlerFunc {
	// your code...
	return nil
}
