// Code generated by hertz generator.

package clinical

import (
	clinical "Hospital/biz/model/clinical"
	"Hospital/biz/pack"
	"Hospital/biz/service"
	"Hospital/pkg/errno"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
)

// AddPatient .
// @router /clinical/patient/add [POST]
func AddPatient(ctx context.Context, c *app.RequestContext) {
	var err error
	var req clinical.AddPatientRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(clinical.AddPatientResponse)
	err = service.NewClinicalService(ctx, c).CreatePatient(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// AddDiagnose .
// @router /clinical/diagnose/add [POST]
func AddDiagnose(ctx context.Context, c *app.RequestContext) {
	var err error
	var req clinical.AddDiagnoseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(clinical.AddDiagnoseResponse)
	err = service.NewClinicalService(ctx, c).CreateDiagnose(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryCase .
// @router /clinical/case/info [GET]
func QueryCase(ctx context.Context, c *app.RequestContext) {
	var err error
	var req clinical.QueryCaseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(clinical.QueryCaseResponse)
	ClinicalResp, count, err := service.NewClinicalService(ctx, c).QueryMedicalCase(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.CaseList(ClinicalResp, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryAllCase .
// @router /clinical/case/all [GET]
func QueryAllCase(ctx context.Context, c *app.RequestContext) {
	var err error
	var req clinical.QueryAllCaseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(clinical.QueryAllCaseResponse)

	v, count, err := service.NewClinicalService(ctx, c).QueryAllMedicalCase(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.CaseList(v, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
