mysql:
  addr: 192.168.1.150:3306
  database: hospital
  username: root
  password: PASSWORD
  charset: utf8mb4

services:
  main:
    name : main
    load-balance: true
    addr:
      - 127.0.0.1:10000