// Code generated by hertz generator.

package biobank

import (
	"Hospital/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(0)
}

func _biobankMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sampleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addsampleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querysamplebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querysamplebypatientMw() []app.HandlerFunc {
	// your code...
	return nil
}
