// Code generated by hertz generator.

package visit

import (
	"Hospital/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(0)
}

func _visitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _try3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addvisitmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryvisitmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}
