package constants

const (
	MySQLDSN          = "root:root@tcp(127.0.0.1:3306)/hospital?charset=utf8mb4&parseTime=true"
	TableAdmin        = "admin"
	TableDoctor       = "doctor"
	TableNurse        = "nurse"
	TablePatient      = "patients"
	TableDiagnose     = "diagnoses"
	TableSymptom      = "symptoms"
	TableVisit        = "follow_up_record"
	TableBioBank      = "biological_samples"
	TableEpidemicCase = "epidemic_case"
	ViewMedicalCase   = "patient_medical_records"
	TableComment      = "comment"
	TableFollower     = "user_follows"
	TableLike         = "video_likes"
	TableVideo        = "video"
	ContextUserId     = "userid"
	TypeKey           = "type"
	AccessTokenKey    = "AccessToken_key"
	RefreshTokenKey   = "Refresh_token_key"
	AvatarStorePath   = "/home/yang/Desktop/resource/avatar"
	VideoStorePath    = "/home/yang/Desktop/resource/video"
	CoverStorePath    = "/home/yang/Desktop/resource/cover"
)
