// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	biobank "Hospital/biz/router/biobank"
	clinical "Hospital/biz/router/clinical"
	epidemic "Hospital/biz/router/epidemic"
	model "Hospital/biz/router/model"
	user "Hospital/biz/router/user"
	visit "Hospital/biz/router/visit"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	biobank.Register(r)

	visit.Register(r)

	clinical.Register(r)

	epidemic.Register(r)

	user.Register(r)

	model.Register(r)

}
